### ISSUE TITLE
Code throws whenever you reach 65536 transactions on a single connection

### ISSUE THREAD

**Issue by jvsanchezo** [samuelventura/SharpModbus#3]
This is due to the fact that transactionId is defined in code as "int" when it should be an "ushort" as defined on Modbus protocol

**Comment by samuelventura** [comment]
Thank you for pointing that out. Can you confirm fix works for you before publishing to nuget?

**Comment by jvsanchezo** [comment]
Yes. We have compiled the library and tested it with success.
