### ISSUE TITLE
.Net Standard 2.0

### ISSUE THREAD

**Issue by ckapatch** [samuelventura/SharpModbus#4]
Hello! very nice little library, are there any plans or possibility to transfer to .Net Standard 2.0? I had a quick look but it looks like it relies on another one of your libraries that is also on .net 4.6.

Thanks again

**Comment by aaasoft** [comment]
1.0.8 version has .NET Standard 2.0 target。
[https://www.nuget.org/packages/SharpModbus/1.0.8](https://www.nuget.org/packages/SharpModbus/1.0.8)

**Comment by ckapatch** [comment]
Thanks @aaasoft. All the best.
